name: portfolio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  url_launcher: ^5.1.4
  url_launcher_web: ^0.1.0
  mailto: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

 uses-material-design: true

assets:
  - assets/images/cover.jpg
  - assets/images/background.jpg
  - assets/images/projects/msunews.jpg
  - assets/images/projects/skillset.jpg
  - assets/images/icons/

fonts:
  - family: Muli
    fonts:
      - asset: assets/fonts/Muli-Light.ttf
        weight: 400
      - asset: assets/fonts/Muli-Regular.ttf
        weight: 500
      - asset: assets/fonts/Muli-Medium.ttf
        weight: 600
      - asset: assets/fonts/Muli-SemiBold.ttf
        weight: 700
      - asset: assets/fonts/Muli-Bold.ttf
        weight: 800